{
 "title": "Demo Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\",namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Request Rate, Error, Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Second by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\", status_code=~\"2.*\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\", status_code=~\"3.*\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\", status_code=~\"4.*\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\", status_code=~\"5.*\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\", status_code=~\"1.*\"}[$__rate_interval]))",
     "legendFormat": "1xx"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\",status_code=~\"(4[0-9][0-9]|5[0-9][0-9])\"}[$__rate_interval])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request Duration Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (job,le) (rate(http_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job,le) (rate(http_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job,le) (rate(http_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "RPS Per: Path, Method, Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (path,method,status_code)",
     "legendFormat": "{{path}} {{method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "RPS Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Errors Per: Path, Method, Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{pod=~\"$pod\",status_code=~\"(4[0-9][0-9]|5[0-9][0-9])\"}[$__rate_interval])",
     "legendFormat": "{{path}} {{method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Request Errors Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$pod\",status_code=~\"(4[0-9][0-9]|5[0-9][0-9])\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "50th Percentile Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (job, path, method, le) (rate(http_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "{{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "95th Percentile Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, path, method, le) (rate(http_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "99th Percentile Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, path, method, le) (rate(http_request_duration_seconds_bucket{pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "NodeJS Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Process CPU Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process Mem Util (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max Event Loop Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(nodejs_eventloop_lag_max_seconds{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(process_open_fds{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Nodejs Active Resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(nodejs_active_resources_total{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} {{type}}"
    }
   ]
  },
  {
   "title": "Nodejs Active Handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(nodejs_active_handles_total{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} {{type}}"
    }
   ]
  },
  {
   "title": "$pod NodeJS Heap Space Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{pod=~\"$pod\"} / nodejs_heap_space_size_total_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{space}}"
    }
   ]
  }
 ]
}